arch:
- aarch64
- amd64
- armhf
- armv7
- i386
boot: manual
codenotary: cas@mathesonsteplock.ca
description: Automatically create and transfer HA backups using SFTP (SCP), rsync,
  or rclone (experimental)
hassio_api: true
hassio_role: manager
homeassistant: 2021.9.0
homeassistant_api: true
image: ikifar/remote-backup-{arch}
init: false
map:
- config
- addons
- share
- ssl
- backup
name: Remote Backup
options:
  backup_custom_prefix: Automated backup
  backup_friendly_name: true
  backup_keep_local: all
  remote_host: null
  remote_key: ''
  remote_port: 22
  remote_user: null
  rsync_enabled: false
  rsync_exclude:
  - /config/*.db-shm
  - /config/*.db-wal
  - /config/*.db
  rsync_rootfolder: hassio-sync
  ssh_enabled: true
  ssh_remote_directory: hassio-backup
schema:
  backup_custom_prefix: str?
  backup_exclude_addons:
  - str?
  backup_exclude_folders:
  - match(^[A-Za-z0-9_\-\.\*\/\?\+\\ ]*$)?
  backup_friendly_name: bool?
  backup_keep_local: match(^(all|null|[+]?\d*)$)?
  backup_password: str?
  debug: bool?
  rclone_copy: bool?
  rclone_enabled: bool?
  rclone_remote_directory: str?
  rclone_remote_host: str?
  rclone_restore: bool?
  rclone_sync: bool?
  remote_host: str
  remote_host_key_algorithms: str?
  remote_key: str?
  remote_password: str?
  remote_port: port
  remote_user: str
  rsync_enabled: bool
  rsync_exclude:
  - match(^[A-Za-z0-9_\-\.\*\/\?\+\\ ]+$)?
  rsync_rootfolder: str?
  ssh_enabled: bool
  ssh_remote_directory: str?
slug: remote_backup
startup: once
url: https://addons.mathesonsteplock.ca/docs/addons/remote-backup/basic-config
version: 2022.12.0
