arch:
- aarch64
- amd64
- armhf
- armv7
- i386
boot: manual
codenotary: cas@mathesonsteplock.ca
description: Automatically create and backup HA backups using SCP
hassio_api: true
hassio_role: manager
homeassistant: 2021.9.0
image: ikifar/remote-backup-{arch}
init: false
map:
- config
- addons
- share
- ssl
- backup:rw
name: Remote Backup
options:
  custom_prefix: Automated backup
  debug: false
  exclude_addons: ''
  exclude_folders: ''
  friendly_name: true
  keep_local_backup: all
  rclone_copy: false
  rclone_enabled: false
  rclone_remote: ''
  rclone_remote_directory: ''
  rclone_restore: false
  rclone_sync: false
  remote_directory: ''
  rsync_enabled: false
  rsync_exclude: ''
  rsync_host: ''
  rsync_password: ''
  rsync_rootfolder: hassio-sync
  rsync_user: ''
  rsync_verbose: false
  ssh_enabled: true
  ssh_host: ''
  ssh_host_key_algorithms: ''
  ssh_key: ''
  ssh_port: 22
  ssh_user: ''
  zip_password: ''
schema:
  custom_prefix: str?
  debug: bool?
  exclude_addons: str?
  exclude_folders: str?
  friendly_name: bool?
  keep_local_backup: match(^(all|[+]?\d*)$)
  rclone_copy: bool?
  rclone_enabled: bool?
  rclone_remote: str?
  rclone_remote_directory: str?
  rclone_restore: bool?
  rclone_sync: bool?
  remote_directory: str?
  rsync_enabled: bool?
  rsync_exclude: str?
  rsync_host: str?
  rsync_password: str?
  rsync_rootfolder: str?
  rsync_user: str?
  rsync_verbose: bool?
  ssh_enabled: bool?
  ssh_host: str?
  ssh_host_key_algorithms: str?
  ssh_key: str?
  ssh_port: int?
  ssh_user: str?
  zip_password: str?
slug: remote_backup
startup: once
url: https://addons.mathesonsteplock.ca/docs/addons/remote-backup/basic-config
version: 2022.7.2
