arch:
- amd64
boot: auto
codenotary: cas@mathesonsteplock.ca
description: GUI application to discover and monitor devices flashed with Tasmota
image: ikifar/tdm-ha-addon
ingress: true
ingress_entry: novnc/vnc_lite.html?resize=scale
init: false
map:
- share:rw
name: Tasmota Device Manager
options:
  debug: false
panel_icon: mdi:application-cog
ports:
  5900/tcp: null
ports_description:
  5900/tcp: TDM via VNC (Not required for Ingress. Not secure!)
schema:
  debug: bool
services:
- mqtt:want
slug: tdm
startup: application
url: https://github.com/ikifar2012/tasmota-device-manager-addon
version: 2022.6.0
