name: Repository Update

on:
  repository_dispatch:
    types: ["update"]

jobs:
  whatever:
    name: Running updater for ${{ github.event.client_payload.addon }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          git config --global user.name ikifar2012
          git config --global user.email "contact@mathesonsteplock.ca"

      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@v1.2.2
        with:
          addon: ${{ github.event.client_payload.addon }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}